### PR TITLE
added thing message

### PR DESCRIPTION
**Pull request by alpsarica**
Too solve the issues in Agent package (adding support for twin features and messages) thing message definition is added.

### CODE REVIEW

**Comment by nacidai** [comment]
Two changes are needed:

1) Please target the new enhancement branch not the main.
2). The headers field in ditto messages includes some important data, see [ProtocolEnvelope](https://eclipse.dev/ditto/protocol-specification.html#dittoProtocolEnvelope).  So please make the headers field explicitly modeled to include the fields from the following example. 


"headers": {
   "reply-to":"att/cbcbcbc",
    "ditto-originator":"nginx:ditto",
    "response-required":false,"
    "content-type":"application/json",
    "correlation-id":"xccv-bababab-09998989-2424242"
}

**Comment by alpsarica** [comment]
@nacidai made the requested changes. Added ThingHeaders message to the Thing message.

**Comment by alpsarica** [comment]
added correlation-id to ThingHeader message

**Comment by nacidai** [comment]
Merging changes related. to https://github.com/eclipse-muto/messages/issues/3

**Pull request merged**
